#ifndef OKC_ED25519_H
#define OKC_ED25519_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Buffer {
  uint8_t *data;
  uintptr_t len;
} Buffer;

struct Buffer okc_ed25519_gen_keypair(void);

struct Buffer okc_ed25519_sign(struct Buffer keypair, struct Buffer msg);

bool okc_ed25519_verify(struct Buffer pubkey, struct Buffer msg, struct Buffer signature);

void free_buf(struct Buffer buf);

#endif /* OKC_ED25519_H */
