version: '3'

services:
  okbchaindnode0:
    container_name: okbchaindnode0
    image: "okbchain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-okbchaind.log}
    volumes:
      - ./build:/okbchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  okbchaindnode1:
    container_name: okbchaindnode1
    image: "okbchain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-okbchaind.log}
    volumes:
      - ./build:/okbchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  okbchaindnode2:
    container_name: okbchaindnode2
    image: "okbchain/node"
    environment:
      - ID=2
      - LOG=${LOG:-okbchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/okbchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  okbchaindnode3:
    container_name: okbchaindnode3
    image: "okbchain/node"
    environment:
      - ID=3
      - LOG=${LOG:-okbchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/okbchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

