// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/okex/exchain/x/distribution/keeper
// ALIASGEN: github.com/okex/exchain/x/distribution/types
// ALIASGEN: github.com/okex/exchain/x/distribution/client
package move

import (
	"github.com/okex/exchain/x/move/keeper"
	"github.com/okex/exchain/x/move/types"
)

const (
	ModuleName        = types.ModuleName
	StoreKey          = types.StoreKey
	RouterKey         = types.RouterKey
	QuerierRoute      = types.QuerierRoute
	DefaultParamspace = types.DefaultParamspace
)

var (
	// functions aliases
	RegisterInvariants = keeper.RegisterInvariants
	NewKeeper          = keeper.NewKeeper
	RegisterCodec      = types.RegisterCodec
	//NewMsgSetWithdrawAddress = types.NewMsgSetWithdrawAddress

	NewQuerier = keeper.NewQuerier

	ValidateGenesis = types.ValidateGenesis

	// variable aliases
	AttributeValueCategory = types.AttributeValueCategory

	ModuleCdc = types.ModuleCdc
)

type (
	Keeper         = keeper.Keeper
	MsgPublishMove = types.MsgPublishMove
	MsgRunMove     = types.MsgRunMove

	GenesisState = types.GenesisState
)
