BIN_NAME=exchaind
CUR=`pwd`
OKCHAIN_TOP="${CUR%/*/*}"
OKCHAIN_BIN=${OKCHAIN_TOP}/build
OKCHAIN_BIN=${GOPATH}/bin
OKCHAIN_NET_CACHE=${CUR}/cache
CHAIN_ID="exchain-67"


BASE_PORT_PREFIX=26600
P2P_PORT_SUFFIX=56
RPC_PORT_SUFFIX=57
REST_PORT=8545
let BASE_PORT=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedp2pport=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedrpcport=${BASE_PORT_PREFIX}+${RPC_PORT_SUFFIX}
let seedrestport=${seedrpcport}+1
