// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReward = "reward"

// Reward mapped from table <reward>
type Reward struct {
	ID        int64      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Height    *int64     `gorm:"column:height;type:int(11)" json:"height"`
	BlockTime *time.Time `gorm:"column:block_time;type:datetime" json:"block_time"`
	Txhash    *string    `gorm:"column:txhash;type:varchar(64)" json:"txhash"`
	Txsender  *string    `gorm:"column:txsender;type:varchar(64)" json:"txsender"`
	Useraddr  *string    `gorm:"column:useraddr;type:varchar(64)" json:"useraddr"`
	Amount    *int64     `gorm:"column:amount;type:int(11)" json:"amount"`
}

// TableName Reward's table name
func (*Reward) TableName() string {
	return TableNameReward
}
