name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test & coverage report creation
        # Some tests, notably TestRandomOperations, are extremely slow in CI
        # with the race detector enabled, so we use -short when -race is
        # enabled to reduce the number of slow tests, and then run without
        # -short with -race disabled for a larger test set.
        #
        # We still run the same tests, just on smaller data sets with -short.
        run: |
          go test ./... -mod=readonly -timeout 15m -short -race -coverprofile=coverage.txt -covermode=atomic
          go test ./... -mod=readonly -timeout 15m
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
