// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/wasm/proto/proposal_custom.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UpdateDeploymentWhitelistProposal struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DistributorAddrs     []string `protobuf:"bytes,3,rep,name=distributorAddrs,proto3" json:"distributorAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeploymentWhitelistProposal) Reset()         { *m = UpdateDeploymentWhitelistProposal{} }
func (m *UpdateDeploymentWhitelistProposal) String() string { return proto.CompactTextString(m) }
func (*UpdateDeploymentWhitelistProposal) ProtoMessage()    {}
func (*UpdateDeploymentWhitelistProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd9d4d6e8a1d82c0, []int{0}
}
func (m *UpdateDeploymentWhitelistProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeploymentWhitelistProposal.Unmarshal(m, b)
}
func (m *UpdateDeploymentWhitelistProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeploymentWhitelistProposal.Marshal(b, m, deterministic)
}
func (m *UpdateDeploymentWhitelistProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeploymentWhitelistProposal.Merge(m, src)
}
func (m *UpdateDeploymentWhitelistProposal) XXX_Size() int {
	return xxx_messageInfo_UpdateDeploymentWhitelistProposal.Size(m)
}
func (m *UpdateDeploymentWhitelistProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeploymentWhitelistProposal.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeploymentWhitelistProposal proto.InternalMessageInfo

func (m *UpdateDeploymentWhitelistProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateDeploymentWhitelistProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateDeploymentWhitelistProposal) GetDistributorAddrs() []string {
	if m != nil {
		return m.DistributorAddrs
	}
	return nil
}

type UpdateWASMContractMethodBlockedListProposal struct {
	Title                string           `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BlockedMethods       *ContractMethods `protobuf:"bytes,3,opt,name=blockedMethods,proto3" json:"blockedMethods,omitempty"`
	IsDelete             bool             `protobuf:"varint,4,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateWASMContractMethodBlockedListProposal) Reset() {
	*m = UpdateWASMContractMethodBlockedListProposal{}
}
func (m *UpdateWASMContractMethodBlockedListProposal) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateWASMContractMethodBlockedListProposal) ProtoMessage() {}
func (*UpdateWASMContractMethodBlockedListProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd9d4d6e8a1d82c0, []int{1}
}
func (m *UpdateWASMContractMethodBlockedListProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWASMContractMethodBlockedListProposal.Unmarshal(m, b)
}
func (m *UpdateWASMContractMethodBlockedListProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWASMContractMethodBlockedListProposal.Marshal(b, m, deterministic)
}
func (m *UpdateWASMContractMethodBlockedListProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWASMContractMethodBlockedListProposal.Merge(m, src)
}
func (m *UpdateWASMContractMethodBlockedListProposal) XXX_Size() int {
	return xxx_messageInfo_UpdateWASMContractMethodBlockedListProposal.Size(m)
}
func (m *UpdateWASMContractMethodBlockedListProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWASMContractMethodBlockedListProposal.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWASMContractMethodBlockedListProposal proto.InternalMessageInfo

func (m *UpdateWASMContractMethodBlockedListProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateWASMContractMethodBlockedListProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateWASMContractMethodBlockedListProposal) GetBlockedMethods() *ContractMethods {
	if m != nil {
		return m.BlockedMethods
	}
	return nil
}

func (m *UpdateWASMContractMethodBlockedListProposal) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type ContractMethods struct {
	ContractAddr         string    `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	Methods              []*Method `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContractMethods) Reset()         { *m = ContractMethods{} }
func (m *ContractMethods) String() string { return proto.CompactTextString(m) }
func (*ContractMethods) ProtoMessage()    {}
func (*ContractMethods) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd9d4d6e8a1d82c0, []int{2}
}
func (m *ContractMethods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractMethods.Unmarshal(m, b)
}
func (m *ContractMethods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractMethods.Marshal(b, m, deterministic)
}
func (m *ContractMethods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractMethods.Merge(m, src)
}
func (m *ContractMethods) XXX_Size() int {
	return xxx_messageInfo_ContractMethods.Size(m)
}
func (m *ContractMethods) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractMethods.DiscardUnknown(m)
}

var xxx_messageInfo_ContractMethods proto.InternalMessageInfo

func (m *ContractMethods) GetContractAddr() string {
	if m != nil {
		return m.ContractAddr
	}
	return ""
}

func (m *ContractMethods) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

type Method struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Extra                string   `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd9d4d6e8a1d82c0, []int{3}
}
func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Method) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type ExtraProposal struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtraProposal) Reset()         { *m = ExtraProposal{} }
func (m *ExtraProposal) String() string { return proto.CompactTextString(m) }
func (*ExtraProposal) ProtoMessage()    {}
func (*ExtraProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd9d4d6e8a1d82c0, []int{4}
}
func (m *ExtraProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraProposal.Unmarshal(m, b)
}
func (m *ExtraProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraProposal.Marshal(b, m, deterministic)
}
func (m *ExtraProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraProposal.Merge(m, src)
}
func (m *ExtraProposal) XXX_Size() int {
	return xxx_messageInfo_ExtraProposal.Size(m)
}
func (m *ExtraProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraProposal.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraProposal proto.InternalMessageInfo

func (m *ExtraProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ExtraProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExtraProposal) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ExtraProposal) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateDeploymentWhitelistProposal)(nil), "types.UpdateDeploymentWhitelistProposal")
	proto.RegisterType((*UpdateWASMContractMethodBlockedListProposal)(nil), "types.UpdateWASMContractMethodBlockedListProposal")
	proto.RegisterType((*ContractMethods)(nil), "types.ContractMethods")
	proto.RegisterType((*Method)(nil), "types.Method")
	proto.RegisterType((*ExtraProposal)(nil), "types.ExtraProposal")
}

func init() {
	proto.RegisterFile("x/wasm/proto/proposal_custom.proto", fileDescriptor_dd9d4d6e8a1d82c0)
}

var fileDescriptor_dd9d4d6e8a1d82c0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x25, 0x4d, 0xdb, 0xd7, 0xde, 0x7e, 0xbc, 0xc7, 0xf0, 0x28, 0xc1, 0x55, 0xcc, 0xc6, 0xa0,
	0xd0, 0x42, 0xdd, 0x0b, 0xad, 0x75, 0x67, 0x41, 0x22, 0x52, 0x70, 0xa1, 0x4c, 0x33, 0x03, 0x1d,
	0x4c, 0x32, 0x61, 0xe6, 0x16, 0xdb, 0x5f, 0xe0, 0xef, 0xf2, 0x9f, 0x49, 0x66, 0xa6, 0xda, 0xd6,
	0xa5, 0x6e, 0xc2, 0x9c, 0x73, 0x72, 0xef, 0x3d, 0xe7, 0x72, 0x21, 0xda, 0x8c, 0x5e, 0xa9, 0xce,
	0x47, 0xa5, 0x92, 0x28, 0xab, 0x6f, 0x29, 0x35, 0xcd, 0x9e, 0xd3, 0xb5, 0x46, 0x99, 0x0f, 0x0d,
	0x4b, 0x1a, 0xb8, 0x2d, 0xb9, 0x8e, 0xde, 0x3c, 0x38, 0x7d, 0x28, 0x19, 0x45, 0x3e, 0xe3, 0x65,
	0x26, 0xb7, 0x39, 0x2f, 0x70, 0xb1, 0x12, 0xc8, 0x33, 0xa1, 0xf1, 0xce, 0x55, 0x92, 0xff, 0xd0,
	0x40, 0x81, 0x19, 0x0f, 0xbc, 0xd0, 0x8b, 0xdb, 0x89, 0x05, 0x24, 0x84, 0x0e, 0xe3, 0x3a, 0x55,
	0xa2, 0x44, 0x21, 0x8b, 0xa0, 0x66, 0xb4, 0x7d, 0x8a, 0x9c, 0xc3, 0x3f, 0x26, 0x34, 0x2a, 0xb1,
	0x5c, 0xa3, 0x54, 0x13, 0xc6, 0x94, 0x0e, 0xfc, 0xd0, 0x8f, 0xdb, 0xc9, 0x37, 0x3e, 0x7a, 0xf7,
	0xe0, 0xc2, 0x3a, 0x59, 0x4c, 0xee, 0xe7, 0xd7, 0xb2, 0x40, 0x45, 0x53, 0x9c, 0x73, 0x5c, 0x49,
	0x36, 0xcd, 0x64, 0xfa, 0xc2, 0xd9, 0xed, 0x6f, 0x78, 0xba, 0x82, 0xfe, 0xd2, 0xb6, 0xb3, 0xbd,
	0x2b, 0x47, 0x5e, 0xdc, 0x19, 0x0f, 0x86, 0x66, 0x23, 0xc3, 0xc3, 0xc9, 0x3a, 0x39, 0xfa, 0x9b,
	0x9c, 0x40, 0x4b, 0xe8, 0x19, 0xcf, 0x38, 0xf2, 0xa0, 0x1e, 0x7a, 0x71, 0x2b, 0xf9, 0xc4, 0xd1,
	0x13, 0xfc, 0x3d, 0x2a, 0x27, 0x11, 0x74, 0x53, 0x47, 0x55, 0x39, 0x9d, 0xdb, 0x03, 0x8e, 0x9c,
	0xc1, 0x9f, 0xdc, 0x79, 0xa9, 0x85, 0x7e, 0xdc, 0x19, 0xf7, 0x9c, 0x17, 0xdb, 0x24, 0xd9, 0xa9,
	0xd1, 0x18, 0x9a, 0x96, 0x22, 0x04, 0xea, 0x05, 0xcd, 0x77, 0xe1, 0xcd, 0xbb, 0xda, 0x08, 0xdf,
	0xa0, 0xa2, 0x2e, 0xb5, 0x05, 0xd1, 0x1a, 0x7a, 0x37, 0xd5, 0xe3, 0xc7, 0x8b, 0x1b, 0x40, 0x93,
	0xa6, 0x46, 0xf4, 0x8d, 0xe8, 0xd0, 0xd7, 0xd8, 0xfa, 0xde, 0xd8, 0x69, 0xff, 0xb1, 0xeb, 0xae,
	0xd0, 0x44, 0x59, 0x36, 0xcd, 0xd9, 0x5d, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xb6, 0x74,
	0x86, 0x9c, 0x02, 0x00, 0x00,
}
